import pandas as pd
import graphs as pb


MAPPING = {
    "salmon-collapse": {
        "filename": "discrease_wild_salmon_1.1.csv",
        "function": pb.make_area_single_chart,
        "parser": pd.read_csv,
        "arguments": [
            "Year",
            "Tons of wild salmon catch in Atlantic waters",
            "Tonnes of wild salmon catch in Atlantic waters",
            [
                '#151c97'
            ],
            "simple_white",
            "",
            True,
        ],
    },
    "hyper-growth": {
        "filename": "hyper_growth_salmon_farming_1.2.csv",
        "function": pb.make_area_order_chart,
        "parser": pd.read_csv,
        "arguments": [
            "Year",
            "Tonnes - live weight",
            "Country",
            "Farmed salmon production by country",
            "Tonnes of farmed salmon produced",
            1975,
            True,
            True,
        ],
    },
    "hyper-growth-grouped": {
        "filename": "numbers_salmons_farmed_1.0.csv",
        "function": pb.make_area_chart_options,
        "parser": pd.read_csv,
        "arguments": [
            "Year",
            "Number of salmons (5kg each)",
            "Farmed salmon production",
            "Number of salmon produced every year",
        ],
    },
    "top-10": {
        "filename": "top_10_countries_producing_1.3.csv",
        "function": pb.make_color_bar_chart,
        "parser": pd.read_csv,
        "arguments": [
            "Tons",
            "Country",
            "Flag",
            "% of total",
            "Top 10 salmon producing countries by tonnes (2021)",
            None,
            None,
            [
                '#151c97', 
                '#ff4530'
            ],
            True,
        ],
    },
    "top-conso": {
        "filename": "top_15_countries_consuming_1.5.csv",
        "function": pb.make_double_yaxis_bar_chart,
        "parser": pd.read_csv,
        "arguments": [
            "Country",
            "Flag",
            "Apparent consumption",
            "Apparent consumption per capita",
            [
                "Production (Capture + Aquaculture)",
                "Export",
                "Import",
            ],
            "Top 15 countries consuming salmon",
            "Country",
            "Apparent consumption in tonnes (2019)",
            "Apparent consumption per capita in kilos (2019)",
            "#151c97",
            "Consumption",
            "#FF4530",
            "Consumption per capita",
            True,
        ],
    },
    "top-comp": {
        "filename": "top_10_companies_producing_2.1.csv",
        "function": pb.make_simple_bar_chart,
        "parser": pd.read_csv,
        "arguments": [
            "Volume, in tons, 2022",
            "Company",
            "Flag",
            "Revenues 2022",
            "Employees 2022",
            [
                "Commercial name",
                "Creation date",
                "Headquarters",
                "Website",
                "Revenues",
                "Employees",
                "Note",
            ],
            "Top 10 companies producing salmon by tonnes (2022)",
            None,
            None,
            "#151c97",
            True,
        ],
    },
    "top-land": {
        "filename": "top_10_ras_companies_2.3.csv",
        "function": pb.make_simple_bar_chart,
        "parser": pd.read_csv,
        "arguments": [
            "Production in tonnes",
            "Parent company",
            "Flag",
            "Revenues 2022 dollars",
            "Employees 2022",
            [
                "Number of projects",
                "Countries of projects",
                "Note",
            ],
            "Top 10 land-based salmon productors (ambitions)",
            "Company ambition for salmon production in tonnes",
            None,
            "#151c97",
            True,
            False,
        ],
    },
    "mortality-rates": {
        "filename": "mortality_rates_4.4.csv",
        "function": pb.make_simple_box_chart,
        "parser": pd.read_csv,
        "arguments": [
            "Company",
            "Mortality_rate",
            "Mortality rates of farmed salmons by producers*",
            "*selected years between 2011-2022 where available",
            "Mortality Rate (%)",
            True,
        ],
    },
    "alternatives": {
        "filename": "alternatives_text_7.csv",
        "function": pb.make_matrix_alternatives,
        "parser": pd.read_csv,
        "arguments": [
            60,
            None,
            None,
            None,
            "Very limited impact",
            "Exces- sively high impact",
            False,
        ],
    },
}

MAPS = {
    "ras-map": {
        "filename": "ras_projects_for_map_2.4.csv",
        "function": pb.make_ras_bubble_map,
        "parser": pd.read_csv,
        "arguments": [
            "Electricity consumption",
            "Carbon footprint",
            "Farms represented by estimated:",
            None,
            True,
            False,
        ],
    },
    "evolution-map": {
        "filename": "evolution_salmon_farming_country_iso_1.4.csv",
        "function": pb.make_animated_bubble_map,
        "parser": pd.read_csv,
        "arguments": [
            "alpha-3",
            "Country",
            "Year",
            "Tonnes - live weight",
            None,
            1980,
            50,
            True,
            [
                '#151c97',
            ],
        ],
    },
}

MAPPINGFR = {
    "salmon-collapse": {
        "filename": "discrease_wild_salmon_1.1_fr.csv",
        "function": pb.make_area_single_chart,
        "parser": pd.read_csv,
        "arguments": [
            "Année",
            "Saumons pêchés dans l'Atlantique en tonnes",
            "Saumons pêchés dans l'Atlantique en tonnes",
            [
                '#151c97'
            ],
            "simple_white",
            "",
            True,
        ],
    },
    "hyper-growth": {
        "filename": "hyper_growth_salmon_farming_1.2_fr.csv",
        "function": pb.make_area_order_chart,
        "parser": pd.read_csv,
        "arguments": [
            "Année",
            "Tonnes de saumons produits en élevage",
            "Pays",
            "Production de saumons atlantiques d'élevage par pays",
            "Tonnes de saumons atlantiques",
            1975,
            True,
            True,
        ],
    },
    "hyper-growth-grouped": {
        "filename": "numbers_salmons_farmed_1.0_fr.csv",
        "function": pb.make_area_chart_options,
        "parser": pd.read_csv,
        "arguments": [
            "Année",
            "Nombre de saumons (5kg chacun)",
            "Production de saumons d'élevage",
            "Nombre de saumons produits chaque année",
        ],
    },   
    "top-10": {
        "filename": "top_10_countries_producing_1.3_fr.csv",
        "function": pb.make_color_bar_chart,
        "parser": pd.read_csv,
        "arguments": [
            "Tonnes de saumon",
            "Pays",
            "Drapeau",
            "% du total",
            "Top 10 pays producteurs de saumons par tonnes (2021)",
            None,
            None,
            [
                '#151c97', 
                '#ff4530'
            ],
            True,
        ],
    },
    "top-conso": {
        "filename": "top_15_countries_consuming_1.5_fr.csv",
        "function": pb.make_double_yaxis_bar_chart,
        "parser": pd.read_csv,
        "arguments": [
            "Pays",
            "Drapeau",
            "Consommation apparente",
            "Consommation apparente par habitant",
            [
                "Production (Capture + Aquaculture)",
                "Export",
                "Import",
            ],
            "Top 15 des pays consommateurs de saumons",
            "Pays",
            "Consommation apparente en tonnes (2019)",
            "Consommation apparente par habitant en kilos (2019)",
            "#151c97",
            "Consommation",
            "#FF4530",
            "Consommation par habitant",
            True,
        ],
    },
    "top-comp": {
        "filename": "top_10_companies_producing_2.1_fr.csv",
        "function": pb.make_simple_bar_chart,
        "parser": pd.read_csv,
        "arguments": [
            "Tonnes de saumon 2022",
            "Producteur",
            "Drapeau",
            "Revenus 2022",
            "Employés 2022",
            [
                "Nom commercial",
                "Date de création",
                "Siège",
                "Site internet",
                "Revenus",
                "Employés",
                "Note",
            ],
            "Top 10 des producteurs de saumons par tonnes (2022)",
            None,
            None,
            "#151c97",
            True,
        ],
    },
    "top-land": {
        "filename": "top_10_ras_companies_2.3_fr.csv",
        "function": pb.make_simple_bar_chart,
        "parser": pd.read_csv,
        "arguments": [
            "Production en tonnes",
            "Producteur",
            "Drapeau",
            "Revenus 2022 dollars",
            "Employés 2022",
            [
                "Nombre de projets",
                "Pays des projets",
                "Note",
            ],
            "Top 10 producteurs de saumons d'élevage terrestre (ambitions)",
            "Ambitions des producteurs pour la production de saumons en tonnes",
            None,
            "#151c97",
            True,
            False,
        ],
    },
    "mortality-rates": {
        "filename": "mortality_rates_4.4_fr.csv",
        "function": pb.make_simple_box_chart,
        "parser": pd.read_csv,
        "arguments": [
            "Producteur",
            "Taux de mortalité",
            "Taux de mortalité des saumons d'élevage par producteurs*",
            "*années sélectionnées entre 2011-2022, lorsque disponibles",
            "Taux de mortalité (%)",
            True,
        ],
    },
    "alternatives": {
        "filename": "alternatives_text_7_fr.csv",
        "function": pb.make_matrix_alternatives,
        "parser": pd.read_csv,
        "arguments": [
            60,
            None,
            None,
            None,
            "Impact très réduit",
            "Impact excessi- vement fort",
            False,
        ],
    },
}

MAPSFR = {
    "ras-map": {
        "filename": "ras_projects_for_map_2.4_fr.csv",
        "function": pb.make_ras_bubble_map,
        "parser": pd.read_csv,
        "arguments": [
            "Consommation d'électricité",
            "Empreinte carbone",
            "Fermes-usines représentées par:",
            None,
            True,
            True
        ],
    },
    "evolution-map": {
        "filename": "evolution_salmon_farming_country_iso_1.4_fr.csv",
        "function": pb.make_animated_bubble_map,
        "parser": pd.read_csv,
        "arguments": [
            "alpha-3",
            "Pays",
            "Année",
            "Tonnes de saumons",
            None,
            1980,
            50,
            True,
            [
                '#151c97',
            ],
        ],
    },
}