name: Build & Deploy to Scaleway

on:
  workflow_dispatch:
  push:
    branches:
    - feat/add-image-build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v3
      with:
        username: nologin
        password: ${{ secrets.SCALEWAY_SECRET_KEY }}
        registry: ${{ secrets.SCALEWAY_CONTAINER_REGISTRY_ENDPOINT }}
    - name: Build the Docker image
      run: docker build . -t ${{ secrets.SCALEWAY_CONTAINER_REGISTRY_ENDPOINT }}/webapp:latest
    - name: Push the Docker Image
      run: docker push ${{ secrets.SCALEWAY_CONTAINER_REGISTRY_ENDPOINT }}/webapp:latest

  deploy:
    runs-on: ubuntu-latest
    name: Deploy on Scaleway Containers
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Scaleway Container Deploy action
        id: deploy
        uses:  philibea/scaleway-containers-deploy@v1.0.5
        with:
            type: deploy
            scw_access_key:  ${{ secrets.SCALEWAY_ACCESS_KEY }}
            scw_secret_key: ${{ secrets.SCALEWAY_SECRET_KEY }}
            scw_containers_namespace_id: "fr-par/0880f1d0-2756-4b18-8950-08141edc5e6e"
            scw_registry: ${{ secrets.SCALEWAY_CONTAINER_REGISTRY_ENDPOINT }}/webapp:latest
    